name: Build Joplin Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm install

    - name: Instalar Dependências
      run: npm ci

    - name: Limpar e Instalar Dependências
      run: |
        rm -rf node_modules package-lock.json
        npm install

    - name: Build Plugin
      run: |
        npm run dist

    - name: Package Joplin Plugin (.jpl)
      run: |
        npx joplin plugin pack .
        mkdir -p artifacts
        mv *.jpl artifacts/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: joplin-plugin
        path: artifacts/*.jpl

    - name: Carregar Artefacto
      uses: actions/upload-artifact@v3
      with:
        name: plugin-joplin
        path: dist/

